name: 05 - 1 - Filters Activity Types

on:
  pull_request:
    types: 
        - opened
        - synchronize
    branches: 
        - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
        - run : echo "running whenever a PR is opened or sync AND  base branch is Main"