name: 06 - context
run-name: 06 - context | DEBUG - ${{inputs.debug}}

on:
    #push:
    workflow_dispatch: 
        inputs:
          debug:
            # this name "debug" is the optional name. so you can change it to every thing. this name will be shown to select from runng work windown in github ui"
            type: boolean
            default: false
env:
    my_WF_var: 'workflow'
    my_WF_over_var: 'workflow'    

jobs:
    echo-jobs:
        runs-on: ubuntu-latest
        env:
            my_WF_var: 'JOB'
            my_WF_over_var: 'JOB'    

        steps:
          - name : display information
            run: |
              echo "event Name ${{github.event_name}}"
              echo "Ref: ${{github.ref}}"
              echo "SHA: ${{github.sha}}"
              echo "Actor: ${{github.actor}}"
              echo "workflow: ${{github.workflow}}"
              echo "Run ID: ${{github.run_id}}"
              echo "Run Number: ${{github.run_number}}"
          - name: Retrieve Variables
            run: |
              echo "varible  Values: ${{vars.My_VAR}}"
              # on github repository page go to setting > select Secrets and Varables under security form right pane > actions > variables tab > create repository variable >define MY_VAR
          - name: print variables
            env:
                my_WF_over_var: 'step'
            run: |
                echo "varible  Values: ${{env.my_WF_var}}"
                echo "varible  OVer Values: ${{env.my_WF_over_var}}"
    echo-jobs2:
        runs-on: ubuntu-latest
        steps:
          - name : display workfellow level variable
            run: |            
                echo "workfellow values $my_WF_var"


             