name: 07 - Using Expressions
# preparing default value on push event. becase there is no default 
#  debug value
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF'}}
# the aboe if statement said: if debug value has set then print ON (thi
#  could be happened on Wokrflow-dispatch) otherwise print OFF ( this could
#  be happend on push event)


on:
    push:
    workflow_dispatch: 
        inputs:
            debug:
                type: boolean
                default: false
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] Print start-up data'
              if: ${{ inputs.debug}}
              # if: inputs.debug # you can run the if condition with this syntax too
              run: |
                echo "Triggered by: ${{ github.event_name}}"
                echo "Branch: ${{ github.ref}}"
                echo "Commit SHA: ${{ github.sha}}"
                echo "Runner OS: ${{ runner.os}}"
            - name: '[debug] Print when triggered from main'
              if: ${{ inputs.debug && github.ref == 'refs/heads/main'}}
              #if: inputs.debug && github.ref == 'refs/heads/main' # you can run if condtion with this syntax too
              run:  echo "I was triggered from main branch"
            - name: '[debug] Greeting'
              run: echo "helo World"

