name:  09 - functions
on: 
    pull_request:
    workflow_dispatch: 
jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Failig step
              run: exit 1
            - name:  I will be skipped
              if: ${{success()}} # if previous step succeed this step will run
              run:  echo "I will print if previous step succedd"
            - name: I will be execute
              if: ${{failure()}}
              run: echo "I will print if any previous steps fails"
            - name: I will execute
              if: ${{!cancelled()}} # you can consider it as alwayes()
              run: echo "I will always print! except when the workfolw is cancelled"
            - name: I will execute when cancelled
              if: ${{cancelled()}}
              run: echo "I will print if the workflow has been cancelled"

