name: 12 - Using outputs

on:
    workflow_dispatch: 
       inputs:
         input-build-status:
            type: choice
            options:
              - success
              - failure
            default: success

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
          build-status: ${{steps.build.outputs.status}} # here status is the key form line status=success
        steps:
            - name: Print GITHUB_OUTPUT path
              run: echo $GITHUB_OUTPUT
            - name: build
              id: build
              run: echo "status=${{inputs.input-build-status}}" >> "$GITHUB_OUTPUT"
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{needs.build.outputs.build-status == 'success'}}
        steps:
            - name: Deploy
              run: echo "Deploying ...."

