name: 13 - using caching
on:
    workflow_dispatch: 
        inputs:
            use-cache:
                description: whenever to execute cache step
                type: boolean
                default: true
            node-version:
                description: Node Version
                type: choice
                options:
                  - 18.x
                  - 20.x
                  - 21.x
                default: 20.x
    

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: 13-caching/react-app
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              # check out done
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{inputs.node-version}}
            - name: Download Cached dep
              uses: actions/cache@v3
              if: ${{inputs.use-cache}}
              id: cache
              with:
                path: 13-caching/react-app/node_modules
                # path is the path that will be saved as a cached at the end of workflow run
                key: deps-node-modules-${{hashFiles('13-caching/react-app/package-lock.json')}}  
            - name: Install dep
              if: steps.cache.outputs.cache-hit != 'true'
              # if there is no cache-hit npm ci will run. else this step will be skipped
              run: npm ci
              # install dependency done
            - name: Testing
              run: npm run test
            - name: Building
              run: npm run build
              # unit testting , building done
            - name: Deploying to nonprod
              run: echo "deploying to nonprod..."
           
        
