name: 15 - working with matrices

on:
    workflow_dispatch: 
jobs:
    backward-compatibility:
        name: ${{matrix.os}}-${{matrix.node-version}}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x ,20.x , 21.x]
                os:
                    - ubuntu:latest
                    - ubuntu:20.04
# by runnig this flow we create 6 job. eac node version will execute
#  on one of os which will run same steps
                include: 
                    - os: ubuntu-latest
                    - node-version: 16.x
# include will add another job with corresponding attr. now we have 7 jobs in the flow.
 #  as you can see with include I run job just for ubuntu and not windows.
        steps:
            - name: checkup steps
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v3
              with: 
                node-version: ${{matrix.node-version}}
            - name: Perform some test
              run: echo "running tests on OS ${{matrix.os}} and Nodejs ${{matrix.node-version}}"
            - name: showing files
              run: ls -R

